### ISSUE TITLE
No 'next' button 'player preparation' page

### ISSUE THREAD

**Issue by lotje1990** [brdgm/carnegie-solo-helper#12]
I tried it today for the first time and for some reason I cannot go further that the 'player preparation' page because there is no 'next' or 'start' button on that page.see screenshot. 

![Screenshot_2024-02-04-11-54-22-43_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/brdgm/carnegie-solo-helper/assets/8875510/3dde6847-5624-4fb9-9fcc-08431ad96077)

**Comment by stefanseifert** [comment]
you have to actually pick a starting department tile (blue button), before the next button appears.
maybe i should add an extra message for this.
