### ISSUE TITLE
Add action marker "gear icon" to Timeline

### ISSUE THREAD

**Issue by lief-erickson** [brdgm/carnegie-solo-helper#4]
To mimic or replicate the physical experience of playing the game, please consider adding the action selection marker to the timeline. 

![carnegie-gear-icon](https://github.com/brdgm/carnegie-solo-helper/assets/10221562/1321a233-ef76-468d-a282-c6cf277e8145)

Doing so makes it clear what the current action is or previously selected action was. Perhaps something like this:

![carnegie-timeline-with-gear-icon](https://github.com/brdgm/carnegie-solo-helper/assets/10221562/089f41fb-ed17-47cc-a26c-4d14bab739da)

Anywhere Timeline code appears, you may want to add the selection marker, especially from Andrew's "Timeline" button.

**Comment by stefanseifert** [comment]
in the timeline action selection screen, the selected action is shown with a orange glow/shadow:
![image](https://github.com/brdgm/carnegie-solo-helper/assets/5614031/7f67c157-a7ef-4139-9e64-f0ebfca82aba)

later in your/andrews turn, that is not the case - but you see what the current action is:
![image](https://github.com/brdgm/carnegie-solo-helper/assets/5614031/e6acfd6c-6a6e-4e75-ac23-50d10615af9b)

do you think it would be more obvious to show the orange glow on the timeline modal dialog as well?

**Comment by lief-erickson** [comment]
On a mobile device, which is where I'd play, the current action is covered by the modal window and is not visible. 

![Screenshot_20231126_171533_Chrome](https://github.com/brdgm/carnegie-solo-helper/assets/10221562/65a72e15-f7c9-41e3-9aa0-1ba09e398d00)


The orange glow/shadow should be on the main timeline too. Because the glow concept won't work beyond the end of the timeline, you'd need to develop a UI concept to indicate timelines chosen for the sixth (or more) time. The gear icon solves the problem. 

Ideally, everything is visible from single timeline view without needing to go into extra modals. Minimizing the number of taps necessary to 1) identify game state and 2) maintain/manage upkeep should be kept to as few as possible.

**Comment by stefanseifert** [comment]
the active selection of action & event is now also shown in the sidebar modal view of the timeline
