### ISSUE TITLE
Select an action more than five times

### ISSUE THREAD

**Issue by lief-erickson** [brdgm/carnegie-solo-helper#5]
It is possible to have an action selected more than five times in a game. I have attempted to do so with the web app but have not figured out how. Is it a bug that I cannot or have I missed something (obvious)?

For example, tapping on the last Management timeline action does nothing.

![carnegie-timeline-select-action](https://github.com/brdgm/carnegie-solo-helper/assets/10221562/cd53c6d7-8145-41a9-a247-e69105ffa3f8)

This is related to #4. Having the selection marker in addition to flipping the region to white might be something to consider.

**Comment by stefanseifert** [comment]
the first column with the blue background are actually buttons. you can select the same action as often as you want (as long as there are still unresolved event spots) - did you try this? maybe i should make it more obvious.

**Comment by lief-erickson** [comment]
I did not identify those as buttons.  I can confirm they work as you describe.

I feel there's an opportunity to improve the UI and UX but I don't have specific ideas at the moment. I'll give it further thought.

**Comment by stefanseifert** [comment]
i've implemtend an improvement for this as well

pushed a new release v1.0.6 together with the other two tickets

thanks for the bug reports!

**Comment by lief-erickson** [comment]
I looked at 1.0.6. 👍
