### ISSUE TITLE
Missing info when selecting action

### ISSUE THREAD

**Issue by lief-erickson** [brdgm/carnegie-solo-helper#6]
Before choosing an action a player is supposed to know two things about Andrew's cards:

1. What his strongest current action is.
2. What action he'll select next turn.

We can see what his best current action is but do not know what he'll select next turn. Based on this image I presume that Andrew's strongest action for _this round_ is unknown because of the **?** icon.

![carnegie-timeline-select-action-info-fehlt](https://github.com/brdgm/carnegie-solo-helper/assets/10221562/2d5b2886-1a44-4d9b-9443-c499a5ee7ecb)

Rulebook (p. 18):
> Tip: Before choosing a Timeline, you should look at two 
things: First, look at the back of that round’s action card, as it 
will indicate which Timeline is currently Andrew’s strongest; 
avoiding this action can help to prevent Andrew from gaining 
too many points. Second, look at the top card of the draw pile, 
which indicates the Timeline that Andrew will choose in the 
next round; this may be valuable in making decisions from 
round to round.

Perhaps something like this would work? I think it could be improved further to indicate current turn and next turn.
![carnegie-andrews-plan](https://github.com/brdgm/carnegie-solo-helper/assets/10221562/2f053ccb-728e-4681-9a9c-91cb89dcc7fc)

**Comment by stefanseifert** [comment]
oh, this was an oversight! i will add that!

**Comment by stefanseifert** [comment]
i've added a preview for andrews action in next turn in the sidebar
